services:
    mysql:
        image: mysql:8
        container_name: jobboard_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jobboard_db
        ports:
            - "3307:3306"
        volumes:
            - job-board_mysql_data:/var/lib/mysql
    adminer:
        image: adminer
        container_name: jobboard_adminer
        restart: unless-stopped
        ports:
            - "8080:8080"

volumes:
    job-board_mysql_data:
